# Mailbox storage location and format
mail_location = maildir:/var/mail-platform/vmail/%d/%n:LAYOUT=fs

# System user and group IDs for vmail
mail_uid = 5000
mail_gid = 5000

# First valid UID/GID allowed to log in
first_valid_uid = 5000
last_valid_uid = 5000

# Quota plugin activation
mail_plugins = $mail_plugins quota

namespace inbox {
  inbox = yes

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
}
