# ClamAV Antivirus Scanner integration for Rspamd
clamav {
  action = "reject";
  symbol = "CLAM_VIRUS";
  type = "clamav";
  servers = "clamav:3310";
  scan_mime_parts = true;
  max_size = 20971520; # 20MB
}
