# Rspamd DKIM Signing Configuration
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
selector = "mail";

### If allow_hdrfrom_mismatch is false, From: header must match authenticated user
allow_hdrfrom_mismatch = true;
allow_hdrfrom_mismatch_sign_networks = true;
allow_username_mismatch = true;

use_domain = "header";
sign_authenticated = true;
use_esld = true;
check_pubkey = true;
